// Package quiz provides the unified adaptive quiz engine.
// All quizzes are generated by a three-layer pipeline:
//  1. Scoring – rank knowledge components by weakness / novelty / recency.
//  2. Orchestrator agent – assigns per-component question directives.
//  3. Component agents – write the actual questions for each directive.
package quiz

import (
	"fmt"
	"hash/fnv"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	classpkg "github.com/studyforge/study-agent/internal/class"
	"github.com/studyforge/study-agent/internal/config"
	"github.com/studyforge/study-agent/internal/sfq"
	"github.com/studyforge/study-agent/internal/state"
	"github.com/studyforge/study-agent/plugins"
	"gopkg.in/yaml.v3"
)

const (
	provenanceTagSectionPrefix   = "src_section:"
	provenanceTagComponentPrefix = "src_component:"
	recentQuizSignalMaxFiles     = 12
	recentGenerationWindow       = 72 * time.Hour
	recentGenerationPenaltyMax   = 0.45
	candidateExplorationRate     = 0.35
)

// ProgressEvent carries a quiz-generation progress update emitted during the
// agent loop so callers can show live tool-call feedback.
type ProgressEvent struct {
	Label  string
	Detail string
	Done   bool
	Err    error
}

// QuizOptions parameterises the adaptive quiz generator.
type QuizOptions struct {
	// AssessmentKind selects which context profile to use (e.g. quiz/exam).
	// Unknown values are normalized to "quiz".
	AssessmentKind string
	// Count is the target number of questions.  Defaults to 10 when zero.
	Count int
	// TypePreference is the preferred sfq question type (e.g. "multiple-choice").
	// Use "context-default" (or empty) to resolve from class profile context.
	TypePreference string
	// Tags, when non-empty, restrict scoring to components whose section tags
	// contain at least one matching tag.
	Tags []string
	// Directives, when non-empty, skip the orchestrator and use this explicit
	// plan. This is useful for chat-driven quiz requests that already selected
	// target components and exact counts.
	Directives []OrchestratorDirective
	// CoverageScope optionally reweights component scores using class coverage
	// settings before candidate selection. Nil auto-loads class coverage config.
	CoverageScope *classpkg.CoverageScope
	// FocusedSections, when non-empty, restricts focused quiz mode to components
	// belonging to sections whose ID or title contains any of the given strings
	// (case-insensitive). Only meaningful when AssessmentKind is "focused".
	FocusedSections []string
	// ProviderOverrides, when non-nil, route each quiz agent to a specific AI
	// provider instead of sharing the single provider passed to NewQuizStream.
	// This enables granular model selection (e.g. a smarter model for the
	// orchestrator, a cheaper one for per-component question generation).
	ProviderOverrides *QuizProviderOverrides
}

// QuizProviderOverrides holds optional per-agent AI providers for a quiz run.
// A nil field falls back to the provider passed to NewQuizStream.
type QuizProviderOverrides struct {
	Orchestrator plugins.AIProvider
	Component    plugins.AIProvider
}

// NewQuiz generates a new adaptive quiz for class using the three-layer
// pipeline and returns the saved quiz and its file path.
func NewQuiz(class string, opts QuizOptions, provider plugins.AIProvider, cfg *config.Config) (*state.Quiz, string, error) {
	return NewQuizStream(class, opts, provider, cfg, nil)
}

// NewQuizStream is like NewQuiz but calls onProgress with agent step events
// so callers can show live tool-call feedback in the UI.
func NewQuizStream(class string, opts QuizOptions, provider plugins.AIProvider, cfg *config.Config, onProgress func(ProgressEvent)) (*state.Quiz, string, error) {
	recentSignals := recentQuizSignals{
		ComponentLastSeen: make(map[string]time.Time),
		QuestionKeys:      make(map[string]bool),
	}

	assessmentKind := classpkg.NormalizeContextProfile(opts.AssessmentKind)
	isFocused := assessmentKind == "focused"
	noteRoster, _ := classpkg.LoadNoteRoster(class)
	if opts.CoverageScope == nil && !isFocused {
		if scope, scopeErr := classpkg.LoadCoverageScope(class, assessmentKind); scopeErr != nil {
			if onProgress != nil {
				onProgress(ProgressEvent{Label: "Load coverage scope", Detail: scopeErr.Error(), Done: true, Err: scopeErr})
			}
		} else {
			opts.CoverageScope = scope
		}
	}
	profileDefaultType := classpkg.ResolveProfileDefaultQuestionType(class, assessmentKind, "multiple-choice")
	profileDefaultType = sfq.NormalizeQuestionType(profileDefaultType, "multiple-choice")
	if strings.EqualFold(strings.TrimSpace(opts.TypePreference), "context-default") {
		opts.TypePreference = ""
	}
	opts.TypePreference = sfq.NormalizeQuestionType(opts.TypePreference, profileDefaultType)
	classProfileContext, ctxErr := classpkg.LoadProfileContextText(class, assessmentKind)
	if ctxErr != nil {
		if onProgress != nil {
			onProgress(ProgressEvent{Label: "Load class context", Detail: ctxErr.Error(), Done: true, Err: ctxErr})
		}
		classProfileContext = ""
	} else if onProgress != nil {
		onProgress(ProgressEvent{Label: "Load class context", Detail: assessmentKind + " profile", Done: true})
	}

	if opts.Count <= 0 {
		if len(opts.Directives) > 0 {
			opts.Count = sumDirectiveQuestionCount(opts.Directives)
		}
		if opts.Count <= 0 {
			opts.Count = 10
		}
	}

	// ── 1. Score components ──────────────────────────────────────────────────
	secIdx, err := state.LoadSectionIndex()
	if err != nil {
		return nil, "", fmt.Errorf("load section index: %w", err)
	}
	cmpIdx, err := state.LoadComponentIndex()
	if err != nil {
		return nil, "", fmt.Errorf("load component index: %w", err)
	}
	scores := ScoreComponents(class, secIdx, cmpIdx)
	if len(opts.Tags) > 0 {
		filtered := make([]ComponentScore, 0, len(scores))
		for _, s := range scores {
			if hasAnyTag(s.Section.Tags, opts.Tags) {
				filtered = append(filtered, s)
			}
		}
		scores = filtered
	}
	if len(scores) == 0 {
		if len(opts.Tags) > 0 {
			return nil, "", fmt.Errorf("no knowledge components found for class %q matching tags %v", class, opts.Tags)
		}
		return nil, "", fmt.Errorf("no knowledge components found for class %q — run 'sfa ingest' first", class)
	}
	if isFocused {
		// In focused mode, filter to the requested sections and skip the recent
		// generation penalty so just-studied material is always included.
		if len(opts.FocusedSections) > 0 {
			filtered := make([]ComponentScore, 0, len(scores))
			for _, s := range scores {
				if focusedSectionMatch(s, opts.FocusedSections) {
					filtered = append(filtered, s)
				}
			}
			scores = filtered
		}
		if len(scores) == 0 {
			return nil, "", fmt.Errorf("no knowledge components found for the specified sections in class %q", class)
		}
	} else {
		if signals, signalErr := loadRecentQuizSignals(class, recentQuizSignalMaxFiles); signalErr == nil {
			recentSignals = signals
			scores = applyRecentGenerationPenalty(scores, recentSignals.ComponentLastSeen, time.Now().UTC(), recentGenerationWindow, recentGenerationPenaltyMax)
		}
		if opts.CoverageScope != nil {
			scores = applyCoverageWeighting(scores, opts.CoverageScope, noteRoster)
			if onProgress != nil {
				onProgress(ProgressEvent{Label: "Apply coverage scope", Detail: fmt.Sprintf("%d group(s)", len(opts.CoverageScope.Groups)), Done: true})
			}
			classProfileContext = mergeCoverageContext(classProfileContext, opts.CoverageScope, noteRoster)
		}
		if len(scores) == 0 {
			return nil, "", fmt.Errorf("coverage scope excluded all knowledge candidates for class %q", class)
		}
	}
	candidates := scores
	if len(opts.Directives) == 0 && !isFocused {
		// Focused mode uses all matching components; other modes diversify.
		candidates = SelectCandidatesDiversified(scores, opts.Count*3, candidateExplorationRate, nil)
	}

	if onProgress != nil {
		onProgress(ProgressEvent{Label: "Score components", Detail: fmt.Sprintf("%d candidates", len(candidates)), Done: true})
	}

	// ── 2. Quiz plan ─────────────────────────────────────────────────────────
	var directives []OrchestratorDirective
	if len(opts.Directives) > 0 {
		directives, err = finalizeExplicitDirectives(opts.Directives, opts.Count, opts.TypePreference)
		if err != nil {
			return nil, "", fmt.Errorf("quiz plan: %w", err)
		}
		if onProgress != nil {
			onProgress(ProgressEvent{Label: "Quiz plan", Detail: fmt.Sprintf("%d manual directive(s)", len(directives)), Done: true})
		}
	} else {
		orcProvider := provider
		if opts.ProviderOverrides != nil && opts.ProviderOverrides.Orchestrator != nil {
			orcProvider = opts.ProviderOverrides.Orchestrator
		}
		if isFocused {
			directives, err = runFocusedOrchestratorAgent(class, classProfileContext, candidates, opts.Count, opts.TypePreference, orcProvider, cfg, onProgress)
		} else {
			directives, err = runOrchestratorAgent(class, assessmentKind, classProfileContext, candidates, opts.Count, opts.TypePreference, orcProvider, cfg, onProgress)
		}
		if err != nil {
			return nil, "", fmt.Errorf("orchestrator: %w", err)
		}
	}

	// ── 3. Component agents ──────────────────────────────────────────────────
	// Build a fast lookup so component agents can access their full scores.
	scoreByComponent := make(map[string]ComponentScore, len(candidates))
	for _, cs := range candidates {
		scoreByComponent[cs.Component.ID] = cs
	}
	directives = applyDirectiveDifficultyGuidance(directives, scoreByComponent)

	// Track which component IDs are already assigned by the orchestrator so
	// we can redistribute failed question counts to backup candidates.
	assignedIDs := make(map[string]bool, len(directives))
	for _, d := range directives {
		assignedIDs[d.ComponentID] = true
	}

	// Resolve the component agent provider (may differ from the orchestrator provider).
	cmpProvider := provider
	if opts.ProviderOverrides != nil && opts.ProviderOverrides.Component != nil {
		cmpProvider = opts.ProviderOverrides.Component
	}

	var allSections []state.QuizSection
	var failedCount int // questions to redistribute
	for _, d := range directives {
		if strings.TrimSpace(d.ComponentID) == "" {
			failedCount += d.QuestionCount
			if onProgress != nil {
				onProgress(ProgressEvent{Label: "Quiz plan", Detail: "directive missing component_id", Done: true, Err: fmt.Errorf("directive missing component_id")})
			}
			continue
		}
		cs, ok := scoreByComponent[d.ComponentID]
		if !ok {
			// Orchestrator referenced an unknown component – skip gracefully.
			failedCount += d.QuestionCount
			if onProgress != nil {
				onProgress(ProgressEvent{Label: "Quiz plan", Detail: fmt.Sprintf("component %s not found in class knowledge", d.ComponentID), Done: true, Err: fmt.Errorf("component %s not found", d.ComponentID)})
			}
			continue
		}
		if strings.TrimSpace(d.SectionID) == "" {
			d.SectionID = cs.Section.ID
		}
		if strings.TrimSpace(d.SectionTitle) == "" {
			d.SectionTitle = cs.Section.Title
		}
		sections, agentErr := runComponentQuestionAgent(assessmentKind, classProfileContext, d, cs, cmpProvider, cfg, onProgress)
		if agentErr != nil {
			// Don't fail the whole quiz for one component failure; emit a progress error.
			if onProgress != nil {
				onProgress(ProgressEvent{Label: "Component " + d.ComponentID, Detail: agentErr.Error(), Done: true, Err: agentErr})
			}
			failedCount += d.QuestionCount
			continue
		}
		allSections = append(allSections, sections...)
	}

	// Redistribute failed question counts to the next-best unused candidates.
	if failedCount > 0 {
		for _, cs := range candidates {
			if failedCount <= 0 {
				break
			}
			if assignedIDs[cs.Component.ID] {
				continue
			}
			assignedIDs[cs.Component.ID] = true
			count := failedCount
			if count > 3 {
				count = 3 // cap per-fallback to avoid overloading one component
			}
			fallbackDir := OrchestratorDirective{
				ComponentID:   cs.Component.ID,
				SectionID:     cs.Section.ID,
				SectionTitle:  cs.Section.Title,
				QuestionCount: count,
				QuestionTypes: []string{opts.TypePreference},
				Angle:         "reinforce understanding",
			}
			sections, agentErr := runComponentQuestionAgent(assessmentKind, classProfileContext, fallbackDir, cs, cmpProvider, cfg, onProgress)
			if agentErr != nil {
				if onProgress != nil {
					onProgress(ProgressEvent{Label: "Fallback " + cs.Component.ID, Detail: agentErr.Error(), Done: true, Err: agentErr})
				}
				continue
			}
			allSections = append(allSections, sections...)
			failedCount -= count
		}
	}

	if len(allSections) == 0 {
		return nil, "", fmt.Errorf("no questions were generated — check provider configuration and logs")
	}

	allSections = filterDuplicateQuestionSections(allSections, recentSignals.QuestionKeys)
	if missing := opts.Count - len(allSections); missing > 0 {
		for _, cs := range candidates {
			if missing <= 0 {
				break
			}
			if assignedIDs[cs.Component.ID] {
				continue
			}
			assignedIDs[cs.Component.ID] = true

			count := missing
			if count > 2 {
				count = 2
			}
			extraDir := OrchestratorDirective{
				ComponentID:   cs.Component.ID,
				SectionID:     cs.Section.ID,
				SectionTitle:  cs.Section.Title,
				QuestionCount: count,
				QuestionTypes: []string{opts.TypePreference},
				Angle:         "novel scenario with different wording",
			}
			sections, agentErr := runComponentQuestionAgent(assessmentKind, classProfileContext, extraDir, cs, cmpProvider, cfg, onProgress)
			if agentErr != nil {
				if onProgress != nil {
					onProgress(ProgressEvent{Label: "Diversity fallback " + cs.Component.ID, Detail: agentErr.Error(), Done: true, Err: agentErr})
				}
				continue
			}
			filtered := filterDuplicateQuestionSections(sections, recentSignals.QuestionKeys)
			if len(filtered) == 0 {
				continue
			}
			allSections = append(allSections, filtered...)
			missing = opts.Count - len(allSections)
		}
	}

	if len(allSections) == 0 {
		return nil, "", fmt.Errorf("all generated questions duplicated recent history — broaden scope or increase question type diversity")
	}

	rebalanceChoiceAnswerPositions(allSections)
	deduplicateQuestionIDs(allSections)

	q := &state.Quiz{
		Title:    fmt.Sprintf("%s Adaptive %s", class, strings.Title(assessmentKind)),
		Class:    class,
		Sections: allSections,
	}
	normalizeQuizProvenance(q)

	return saveQuiz(class, assessmentKind, q)
}

func applyDirectiveDifficultyGuidance(directives []OrchestratorDirective, scoreByComponent map[string]ComponentScore) []OrchestratorDirective {
	if len(directives) == 0 || len(scoreByComponent) == 0 {
		return directives
	}
	out := make([]OrchestratorDirective, len(directives))
	for i, directive := range directives {
		out[i] = directive
		score, ok := scoreByComponent[directive.ComponentID]
		if !ok {
			continue
		}
		supplement := directiveDifficultySupplement(score)
		if supplement == "" {
			continue
		}
		if strings.TrimSpace(out[i].Angle) == "" {
			out[i].Angle = supplement
			continue
		}
		out[i].Angle = strings.TrimSpace(out[i].Angle) + "; " + supplement
	}
	return out
}

func directiveDifficultySupplement(score ComponentScore) string {
	switch score.DifficultyBand {
	case "supportive":
		return "difficulty:supportive; begin with simpler confidence-building checks and concrete examples"
	case "advanced":
		if score.ThoughtProvoking >= 0.60 {
			return "difficulty:advanced-mixed; include cross-concept transfer but mix in one direct check"
		}
		return "difficulty:advanced; increase challenge with cross-concept overlap and thought-provoking reasoning"
	default:
		return "difficulty:balanced; mix straightforward checks with moderate reasoning"
	}
}

func finalizeExplicitDirectives(directives []OrchestratorDirective, targetCount int, defaultType string) ([]OrchestratorDirective, error) {
	if len(directives) == 0 {
		return nil, fmt.Errorf("at least one directive is required")
	}
	out := make([]OrchestratorDirective, len(directives))
	remaining := targetCount
	unspecified := 0

	for i, directive := range directives {
		directive.ComponentID = strings.TrimSpace(directive.ComponentID)
		directive.SectionID = strings.TrimSpace(directive.SectionID)
		directive.SectionTitle = strings.TrimSpace(directive.SectionTitle)
		directive.Angle = strings.TrimSpace(directive.Angle)
		if directive.Angle == "" {
			directive.Angle = "check understanding"
		}
		if len(directive.QuestionTypes) == 0 {
			directive.QuestionTypes = []string{defaultType}
		}
		for j := range directive.QuestionTypes {
			directive.QuestionTypes[j] = strings.TrimSpace(directive.QuestionTypes[j])
		}
		if directive.QuestionCount < 0 {
			return nil, fmt.Errorf("directive %d has negative question_count", i+1)
		}
		if directive.QuestionCount == 0 {
			unspecified++
		} else {
			remaining -= directive.QuestionCount
		}
		out[i] = directive
	}

	if targetCount <= 0 {
		for i := range out {
			if out[i].QuestionCount <= 0 {
				out[i].QuestionCount = 1
			}
		}
		return out, nil
	}
	if remaining < 0 {
		return nil, fmt.Errorf("directive question_count exceeds requested total of %d", targetCount)
	}
	if unspecified == 0 {
		if remaining != 0 {
			return nil, fmt.Errorf("directive question_count totals %d but requested count is %d", targetCount-remaining, targetCount)
		}
		return out, nil
	}
	if remaining < unspecified {
		return nil, fmt.Errorf("requested count %d is too small for %d directive(s) with unspecified question_count", targetCount, unspecified)
	}

	for i := range out {
		if out[i].QuestionCount > 0 {
			continue
		}
		out[i].QuestionCount = 1
		remaining--
	}
	for i := range out {
		if remaining == 0 {
			break
		}
		out[i].QuestionCount++
		remaining--
	}
	return out, nil
}

func sumDirectiveQuestionCount(directives []OrchestratorDirective) int {
	total := 0
	for _, directive := range directives {
		if directive.QuestionCount > 0 {
			total += directive.QuestionCount
			continue
		}
		total++
	}
	return total
}

// LoadQuiz reads and unmarshals a quiz YAML file from path.
func LoadQuiz(path string) (*state.Quiz, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read quiz file %q: %w", path, err)
	}
	var q state.Quiz
	if err := yaml.Unmarshal(data, &q); err != nil {
		return nil, fmt.Errorf("parse quiz file %q: %w", path, err)
	}
	return &q, nil
}

// ── internal helpers ──────────────────────────────────────────────────────────

func cleanYAML(resp string) string {
	s := strings.TrimSpace(resp)
	if strings.HasPrefix(s, "```yaml") {
		s = strings.TrimPrefix(s, "```yaml")
	} else if strings.HasPrefix(s, "```") {
		s = strings.TrimPrefix(s, "```")
	}
	s = strings.TrimSuffix(s, "```")
	return strings.TrimSpace(s)
}

func mergeCoverageContext(base string, scope *classpkg.CoverageScope, roster *classpkg.NoteRoster) string {
	if scope == nil || len(scope.Groups) == 0 {
		return base
	}
	var lines []string
	lines = append(lines, "Coverage priorities:")
	for i, group := range scope.Groups {
		patterns := classpkg.ResolveGroupPatterns(group, roster)
		detail := ""
		if len(patterns) > 0 {
			detail = strings.Join(patterns, ", ")
		} else if len(group.Tags) > 0 {
			detail = "tags=" + strings.Join(group.Tags, ",")
		} else {
			detail = "(no match hints)"
		}
		lines = append(lines, fmt.Sprintf("- group %d weight=%.2f :: %s", i+1, group.Weight, detail))
	}
	if scope.ExcludeUnmatched {
		lines = append(lines, "- unmatched material excluded")
	}
	coverageText := strings.Join(lines, "\n")
	if strings.TrimSpace(base) == "" {
		return coverageText
	}
	return strings.TrimSpace(base) + "\n\n" + coverageText
}

func normalizeQuizProvenance(q *state.Quiz) {
	if q == nil {
		return
	}
	for i := range q.Sections {
		sectionIDFromTag, componentIDFromTag := extractProvenanceFromTags(q.Sections[i].Tags)
		if strings.TrimSpace(q.Sections[i].SectionID) == "" {
			q.Sections[i].SectionID = sectionIDFromTag
		}
		if strings.TrimSpace(q.Sections[i].ComponentID) == "" {
			q.Sections[i].ComponentID = componentIDFromTag
		}
		if q.Sections[i].SectionID != "" && !hasPrefixedTag(q.Sections[i].Tags, provenanceTagSectionPrefix, q.Sections[i].SectionID) {
			q.Sections[i].Tags = append(q.Sections[i].Tags, provenanceTagSectionPrefix+q.Sections[i].SectionID)
		}
		if q.Sections[i].ComponentID != "" && !hasPrefixedTag(q.Sections[i].Tags, provenanceTagComponentPrefix, q.Sections[i].ComponentID) {
			q.Sections[i].Tags = append(q.Sections[i].Tags, provenanceTagComponentPrefix+q.Sections[i].ComponentID)
		}
	}
}

func extractProvenanceFromTags(tags []string) (sectionID, componentID string) {
	for _, tag := range tags {
		normalized := strings.TrimSpace(tag)
		if sectionID == "" && strings.HasPrefix(strings.ToLower(normalized), provenanceTagSectionPrefix) {
			sectionID = strings.TrimSpace(normalized[len(provenanceTagSectionPrefix):])
		}
		if componentID == "" && strings.HasPrefix(strings.ToLower(normalized), provenanceTagComponentPrefix) {
			componentID = strings.TrimSpace(normalized[len(provenanceTagComponentPrefix):])
		}
	}
	return sectionID, componentID
}

func hasPrefixedTag(tags []string, prefix, value string) bool {
	needle := strings.ToLower(strings.TrimSpace(prefix + value))
	for _, tag := range tags {
		if strings.ToLower(strings.TrimSpace(tag)) == needle {
			return true
		}
	}
	return false
}

func saveQuiz(class, prefix string, q *state.Quiz) (*state.Quiz, string, error) {
	quizID := fmt.Sprintf("%s-%d", prefix, time.Now().Unix())
	quizPath, err := config.Path("quizzes", class, quizID+".yaml")
	if err != nil {
		return nil, "", err
	}
	if err := os.MkdirAll(filepath.Dir(quizPath), 0755); err != nil {
		return nil, "", fmt.Errorf("create quiz dir: %w", err)
	}
	data, err := yaml.Marshal(q)
	if err != nil {
		return nil, "", fmt.Errorf("marshal quiz: %w", err)
	}
	if err := os.WriteFile(quizPath, data, 0644); err != nil {
		return nil, "", fmt.Errorf("write quiz: %w", err)
	}
	sfqPath := strings.TrimSuffix(quizPath, ".yaml") + ".sfq"
	if err := os.WriteFile(sfqPath, quizToSFQ(q), 0644); err != nil {
		return nil, "", fmt.Errorf("write sfq file: %w", err)
	}
	return q, quizPath, nil
}

// quizToSFQ converts a Quiz to the .sfq block-delimiter format expected by the
// sfq binary.  Each QuizSection is rendered according to its question type so
// that all six sfq types (multiple-choice, multi-select, true-false,
// multi-true-false, short-answer, ordering) are natively supported.
func quizToSFQ(q *state.Quiz) []byte {
	var b strings.Builder
	if q.Title != "" {
		fmt.Fprintf(&b, "# %s\n\n", q.Title)
	}
	for _, sec := range q.Sections {
		b.WriteString("---\n")
		if sec.ID != "" {
			fmt.Fprintf(&b, "id: %s\n", sec.ID)
		}
		if sec.Type != "" {
			fmt.Fprintf(&b, "type: %s\n", sec.Type)
		}
		if sec.Hint != "" {
			fmt.Fprintf(&b, "hint: %q\n", sec.Hint)
		}
		if len(sec.Tags) > 0 {
			fmt.Fprintf(&b, "tags: [%s]\n", strings.Join(sec.Tags, ", "))
		}
		fmt.Fprintf(&b, "? %s\n", sec.Question)

		switch sec.Type {
		case "multiple-choice", "multi-select":
			for _, ch := range sec.Choices {
				mark := "[ ]"
				if ch.Correct {
					mark = "[x]"
				}
				fmt.Fprintf(&b, "- %s %s\n", mark, ch.Text)
			}
		case "true-false":
			// Choices should be [True, False] — emit in answer order.
			if len(sec.Choices) >= 2 {
				for _, ch := range sec.Choices {
					mark := "[ ]"
					if ch.Correct {
						mark = "[x]"
					}
					fmt.Fprintf(&b, "- %s %s\n", mark, ch.Text)
				}
			} else if sec.Answer != "" {
				correct := strings.EqualFold(strings.TrimSpace(sec.Answer), "true")
				if correct {
					b.WriteString("- [x] True\n- [ ] False\n")
				} else {
					b.WriteString("- [ ] True\n- [x] False\n")
				}
			}
		case "multi-true-false":
			for _, ch := range sec.Choices {
				mark := "[F]"
				if ch.Correct {
					mark = "[T]"
				}
				fmt.Fprintf(&b, "- %s %s\n", mark, ch.Text)
			}
		case "ordering":
			for i, ch := range sec.Choices {
				fmt.Fprintf(&b, "%d. %s\n", i+1, ch.Text)
			}
		default:
			// short-answer and unknown types: emit plain answer field.
			if sec.Answer != "" {
				fmt.Fprintf(&b, "answer: %q\n", sec.Answer)
			}
		}

		if sec.Reasoning != "" {
			fmt.Fprintf(&b, "explanation: %s\n", sec.Reasoning)
		}
		b.WriteString("\n")
	}
	b.WriteString("---\n")
	return []byte(b.String())
}

// deduplicateQuestionIDs assigns globally unique sequential IDs to all
// sections.  Each LLM component agent independently starts its ID counter
// from q-001, so collisions are guaranteed when sections are merged.
// IDs are reformatted as q-001, q-002, … after combining all agents' output.
func deduplicateQuestionIDs(sections []state.QuizSection) {
	for i := range sections {
		sections[i].ID = fmt.Sprintf("q-%03d", i+1)
	}
}

// rebalanceChoiceAnswerPositions spreads answer patterns across choice-based
// question types while preserving question correctness. This is deterministic
// so tests and quiz rendering are stable across runs.
func rebalanceChoiceAnswerPositions(sections []state.QuizSection) {
	for i := range sections {
		sec := &sections[i]
		if len(sec.Choices) < 2 {
			continue
		}

		switch sec.Type {
		case "multiple-choice", "true-false":
			rebalanceSingleCorrectChoice(sec)
		case "multi-select", "multi-true-false":
			sec.Choices = stableShuffleChoices(*sec, sec.Choices)
		case "ordering":
			// Keep ordering unchanged: list order encodes the canonical answer.
			continue
		default:
			continue
		}
	}
}

func rebalanceSingleCorrectChoice(sec *state.QuizSection) {
	if sec == nil || len(sec.Choices) < 2 {
		return
	}

	correctIdx := -1
	correctCount := 0
	for j, ch := range sec.Choices {
		if ch.Correct {
			correctCount++
			correctIdx = j
		}
	}
	if correctCount != 1 || correctIdx < 0 {
		return
	}

	targetIdx := stableChoiceTarget(*sec, len(sec.Choices))
	if targetIdx == correctIdx {
		return
	}
	sec.Choices = moveChoice(sec.Choices, correctIdx, targetIdx)
}

func stableShuffleChoices(sec state.QuizSection, choices []state.QuizChoice) []state.QuizChoice {
	if len(choices) < 2 {
		return choices
	}

	type rankedChoice struct {
		choice state.QuizChoice
		rank   uint32
		idx    int
	}
	ranked := make([]rankedChoice, len(choices))
	for i, ch := range choices {
		h := fnv.New32a()
		_, _ = h.Write([]byte(stableChoiceSeed(sec)))
		_, _ = h.Write([]byte("|" + strings.ToLower(strings.TrimSpace(ch.Text))))
		_, _ = h.Write([]byte(fmt.Sprintf("|%d", i)))
		ranked[i] = rankedChoice{choice: ch, rank: h.Sum32(), idx: i}
	}
	sort.Slice(ranked, func(i, j int) bool {
		if ranked[i].rank == ranked[j].rank {
			return ranked[i].idx < ranked[j].idx
		}
		return ranked[i].rank < ranked[j].rank
	})
	out := make([]state.QuizChoice, len(choices))
	for i := range ranked {
		out[i] = ranked[i].choice
	}
	return out
}

func stableChoiceTarget(sec state.QuizSection, size int) int {
	if size <= 1 {
		return 0
	}
	h := fnv.New32a()
	_, _ = h.Write([]byte(stableChoiceSeed(sec)))
	return int(h.Sum32() % uint32(size))
}

func stableChoiceSeed(sec state.QuizSection) string {
	return strings.ToLower(strings.TrimSpace(sec.Question)) +
		"|" + strings.TrimSpace(sec.SectionID) +
		"|" + strings.TrimSpace(sec.ComponentID) +
		"|" + strings.TrimSpace(sec.Type)
}

func moveChoice(choices []state.QuizChoice, from, to int) []state.QuizChoice {
	if from < 0 || to < 0 || from >= len(choices) || to >= len(choices) || from == to {
		return choices
	}
	moved := choices[from]
	if from < to {
		copy(choices[from:to], choices[from+1:to+1])
	} else {
		copy(choices[to+1:from+1], choices[to:from])
	}
	choices[to] = moved
	return choices
}

type recentQuizSignals struct {
	ComponentLastSeen map[string]time.Time
	QuestionKeys      map[string]bool
}

func loadRecentQuizSignals(class string, maxFiles int) (recentQuizSignals, error) {
	signals := recentQuizSignals{
		ComponentLastSeen: make(map[string]time.Time),
		QuestionKeys:      make(map[string]bool),
	}
	if maxFiles <= 0 {
		return signals, nil
	}

	quizDir, err := config.Path("quizzes", class)
	if err != nil {
		return signals, err
	}
	entries, err := os.ReadDir(quizDir)
	if err != nil {
		if os.IsNotExist(err) {
			return signals, nil
		}
		return signals, fmt.Errorf("read quiz directory: %w", err)
	}

	type quizFile struct {
		path    string
		modTime time.Time
	}
	files := make([]quizFile, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".yaml" {
			continue
		}
		info, infoErr := entry.Info()
		if infoErr != nil {
			continue
		}
		files = append(files, quizFile{
			path:    filepath.Join(quizDir, entry.Name()),
			modTime: info.ModTime().UTC(),
		})
	}
	sort.Slice(files, func(i, j int) bool {
		return files[i].modTime.After(files[j].modTime)
	})
	if len(files) > maxFiles {
		files = files[:maxFiles]
	}

	for _, file := range files {
		q, loadErr := LoadQuiz(file.path)
		if loadErr != nil {
			continue
		}
		normalizeQuizProvenance(q)
		for _, sec := range q.Sections {
			componentID := strings.TrimSpace(sec.ComponentID)
			if componentID == "" {
				_, componentID = extractProvenanceFromTags(sec.Tags)
			}
			if componentID != "" {
				if last, ok := signals.ComponentLastSeen[componentID]; !ok || file.modTime.After(last) {
					signals.ComponentLastSeen[componentID] = file.modTime
				}
			}
			if key := normalizeQuestionKey(sec.Question); key != "" {
				signals.QuestionKeys[key] = true
			}
		}
	}

	return signals, nil
}

func applyRecentGenerationPenalty(scores []ComponentScore, recent map[string]time.Time, now time.Time, window time.Duration, maxPenalty float64) []ComponentScore {
	if len(scores) == 0 || len(recent) == 0 || window <= 0 || maxPenalty <= 0 {
		return scores
	}
	if maxPenalty > 0.95 {
		maxPenalty = 0.95
	}

	out := make([]ComponentScore, len(scores))
	copy(out, scores)

	windowSeconds := window.Seconds()
	for i := range out {
		componentID := strings.TrimSpace(out[i].Component.ID)
		seenAt, ok := recent[componentID]
		if !ok {
			continue
		}
		age := now.Sub(seenAt)
		if age < 0 {
			age = 0
		}
		if age >= window {
			continue
		}
		freshness := 1 - (age.Seconds() / windowSeconds)
		penalty := maxPenalty * freshness
		out[i].Score = out[i].Score * (1 - penalty)
	}

	sort.Slice(out, func(i, j int) bool {
		return out[i].Score > out[j].Score
	})
	return out
}

func filterDuplicateQuestionSections(sections []state.QuizSection, seen map[string]bool) []state.QuizSection {
	if len(sections) == 0 {
		return sections
	}
	if seen == nil {
		seen = make(map[string]bool)
	}

	out := make([]state.QuizSection, 0, len(sections))
	for _, sec := range sections {
		key := normalizeQuestionKey(sec.Question)
		if key != "" {
			if seen[key] {
				continue
			}
			seen[key] = true
		}
		out = append(out, sec)
	}
	return out
}

func normalizeQuestionKey(question string) string {
	question = strings.ToLower(strings.TrimSpace(question))
	if question == "" {
		return ""
	}
	return strings.Join(strings.Fields(question), " ")
}

func hasAnyTag(noteTags, filter []string) bool {
	set := make(map[string]bool, len(noteTags))
	for _, t := range noteTags {
		set[strings.ToLower(t)] = true
	}
	for _, t := range filter {
		if set[strings.ToLower(t)] {
			return true
		}
	}
	return false
}

// focusedSectionMatch reports whether a component score belongs to a section
// that matches any of the targets by exact ID or case-insensitive title
// substring.
func focusedSectionMatch(cs ComponentScore, targets []string) bool {
	sectionID := strings.ToLower(strings.TrimSpace(cs.Section.ID))
	sectionTitle := strings.ToLower(strings.TrimSpace(cs.Section.Title))
	for _, t := range targets {
		t = strings.ToLower(strings.TrimSpace(t))
		if t == "" {
			continue
		}
		if t == sectionID || strings.Contains(sectionTitle, t) {
			return true
		}
	}
	return false
}
