// Package quiz provides the unified adaptive quiz engine.
// All quizzes are generated by a three-layer pipeline:
//  1. Scoring – rank knowledge components by weakness / novelty / recency.
//  2. Orchestrator agent – assigns per-component question directives.
//  3. Component agents – write the actual questions for each directive.
package quiz

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	classpkg "github.com/studyforge/study-agent/internal/class"
	"github.com/studyforge/study-agent/internal/config"
	"github.com/studyforge/study-agent/internal/repository"
	"github.com/studyforge/study-agent/internal/sfq"
	"github.com/studyforge/study-agent/internal/state"
	"github.com/studyforge/study-agent/plugins"
	"gopkg.in/yaml.v3"
)

const (
	recentQuizSignalMaxFiles   = 12
	recentGenerationWindow     = 72 * time.Hour
	recentGenerationPenaltyMax = 0.45
	candidateExplorationRate   = 0.35
)

// ProgressEvent carries a quiz-generation progress update emitted during the
// agent loop so callers can show live tool-call feedback.
type ProgressEvent struct {
	Label  string
	Detail string
	Done   bool
	Err    error
}

// QuizOptions parameterises the adaptive quiz generator.
type QuizOptions struct {
	// AssessmentKind selects which context profile to use (e.g. quiz/exam).
	// Unknown values are normalized to "quiz".
	AssessmentKind string
	// Count is the target number of questions.  Defaults to 10 when zero.
	Count int
	// TypePreference is the preferred sfq question type (e.g. "multiple-choice").
	// Use "context-default" (or empty) to resolve from class profile context.
	TypePreference string
	// Tags, when non-empty, restrict scoring to components whose section tags
	// contain at least one matching tag.
	Tags []string
	// Directives, when non-empty, skip the orchestrator and use this explicit
	// plan. This is useful for chat-driven quiz requests that already selected
	// target components and exact counts.
	Directives []OrchestratorDirective
	// CoverageScope optionally reweights component scores using class coverage
	// settings before candidate selection. Nil auto-loads class coverage config.
	CoverageScope *classpkg.CoverageScope
	// FocusedSections, when non-empty, restricts focused quiz mode to components
	// belonging to sections whose ID or title contains any of the given strings
	// (case-insensitive). Only meaningful when AssessmentKind is "focused".
	FocusedSections []string
	// ProviderOverrides, when non-nil, route each quiz agent to a specific AI
	// provider instead of sharing the single provider passed to NewQuizStream.
	// This enables granular model selection (e.g. a smarter model for the
	// orchestrator, a cheaper one for per-component question generation).
	ProviderOverrides *QuizProviderOverrides
}

// QuizProviderOverrides holds optional per-agent AI providers for a quiz run.
// A nil field falls back to the provider passed to NewQuizStream.
type QuizProviderOverrides struct {
	Orchestrator plugins.AIProvider
	Component    plugins.AIProvider
}

// NewQuiz generates a new adaptive quiz for class using the three-layer
// pipeline and returns the saved quiz and its file path.
func NewQuiz(class string, opts QuizOptions, provider plugins.AIProvider, cfg *config.Config) (*state.Quiz, string, error) {
	return NewQuizWithStore(class, opts, provider, cfg, nil)
}

// NewQuizStream is like NewQuiz but calls onProgress with agent step events
// so callers can show live tool-call feedback in the UI.
func NewQuizStream(class string, opts QuizOptions, provider plugins.AIProvider, cfg *config.Config, onProgress func(ProgressEvent)) (*state.Quiz, string, error) {
	return NewQuizStreamWithStore(class, opts, provider, cfg, nil, onProgress)
}

// NewQuizWithStore generates a new adaptive quiz using the provided store.
func NewQuizWithStore(class string, opts QuizOptions, provider plugins.AIProvider, cfg *config.Config, store repository.Store) (*state.Quiz, string, error) {
	return NewQuizStreamWithStore(class, opts, provider, cfg, store, nil)
}

// NewQuizStreamWithStore is like NewQuizStream but reads persisted data from
// the provided repository store.
func NewQuizStreamWithStore(class string, opts QuizOptions, provider plugins.AIProvider, cfg *config.Config, store repository.Store, onProgress func(ProgressEvent)) (*state.Quiz, string, error) {
	recentSignals := recentQuizSignals{
		ComponentLastSeen: make(map[string]time.Time),
		QuestionKeys:      make(map[string]bool),
	}
	resolvedStore := resolveStore(store)

	assessmentKind := classpkg.NormalizeContextProfile(opts.AssessmentKind)
	isFocused := assessmentKind == "focused"
	noteRoster, _ := classpkg.LoadNoteRoster(class)
	if opts.CoverageScope == nil && !isFocused {
		if scope, scopeErr := classpkg.LoadCoverageScope(class, assessmentKind); scopeErr != nil {
			if onProgress != nil {
				onProgress(ProgressEvent{Label: "Load coverage scope", Detail: scopeErr.Error(), Done: true, Err: scopeErr})
			}
		} else {
			opts.CoverageScope = scope
		}
	}
	profileDefaultType := classpkg.ResolveProfileDefaultQuestionType(class, assessmentKind, "multiple-choice")
	profileDefaultType = sfq.NormalizeQuestionType(profileDefaultType, "multiple-choice")
	if strings.EqualFold(strings.TrimSpace(opts.TypePreference), "context-default") {
		opts.TypePreference = ""
	}
	opts.TypePreference = sfq.NormalizeQuestionType(opts.TypePreference, profileDefaultType)
	classProfileContext, ctxErr := classpkg.LoadProfileContextText(class, assessmentKind)
	if ctxErr != nil {
		if onProgress != nil {
			onProgress(ProgressEvent{Label: "Load class context", Detail: ctxErr.Error(), Done: true, Err: ctxErr})
		}
		classProfileContext = ""
	} else if onProgress != nil {
		onProgress(ProgressEvent{Label: "Load class context", Detail: assessmentKind + " profile", Done: true})
	}

	if opts.Count <= 0 {
		if len(opts.Directives) > 0 {
			opts.Count = sumDirectiveQuestionCount(opts.Directives)
		}
		if opts.Count <= 0 {
			opts.Count = 10
		}
	}

	// ── 1. Score components ──────────────────────────────────────────────────
	secIdx, err := resolvedStore.Knowledge().LoadSectionIndex()
	if err != nil {
		return nil, "", fmt.Errorf("load section index: %w", err)
	}
	cmpIdx, err := resolvedStore.Knowledge().LoadComponentIndex()
	if err != nil {
		return nil, "", fmt.Errorf("load component index: %w", err)
	}
	scores := ScoreComponents(class, secIdx, cmpIdx)
	if len(opts.Tags) > 0 {
		filtered := make([]ComponentScore, 0, len(scores))
		for _, s := range scores {
			if hasAnyTag(s.Section.Tags, opts.Tags) {
				filtered = append(filtered, s)
			}
		}
		scores = filtered
	}
	if len(scores) == 0 {
		if len(opts.Tags) > 0 {
			return nil, "", fmt.Errorf("no knowledge components found for class %q matching tags %v", class, opts.Tags)
		}
		return nil, "", fmt.Errorf("no knowledge components found for class %q — run 'sfa ingest' first", class)
	}
	if isFocused {
		if len(opts.FocusedSections) > 0 {
			filtered := make([]ComponentScore, 0, len(scores))
			for _, s := range scores {
				if focusedSectionMatch(s, opts.FocusedSections) {
					filtered = append(filtered, s)
				}
			}
			scores = filtered
		}
		if len(scores) == 0 {
			return nil, "", fmt.Errorf("no knowledge components found for the specified sections in class %q", class)
		}
	} else {
		if signals, signalErr := loadRecentQuizSignals(class, recentQuizSignalMaxFiles); signalErr == nil {
			recentSignals = signals
			scores = applyRecentGenerationPenalty(scores, recentSignals.ComponentLastSeen, time.Now().UTC(), recentGenerationWindow, recentGenerationPenaltyMax)
		}
		if opts.CoverageScope != nil {
			scores = applyCoverageWeighting(scores, opts.CoverageScope, noteRoster)
			if onProgress != nil {
				onProgress(ProgressEvent{Label: "Apply coverage scope", Detail: fmt.Sprintf("%d group(s)", len(opts.CoverageScope.Groups)), Done: true})
			}
			classProfileContext = mergeCoverageContext(classProfileContext, opts.CoverageScope, noteRoster)
		}
		if len(scores) == 0 {
			return nil, "", fmt.Errorf("coverage scope excluded all knowledge candidates for class %q", class)
		}
	}
	candidates := scores
	if len(opts.Directives) == 0 && !isFocused {
		candidates = SelectCandidatesDiversified(scores, opts.Count*3, candidateExplorationRate, nil)
	}

	if onProgress != nil {
		onProgress(ProgressEvent{Label: "Score components", Detail: fmt.Sprintf("%d candidates", len(candidates)), Done: true})
	}

	// ── 2. Quiz plan ─────────────────────────────────────────────────────────
	var directives []OrchestratorDirective
	if len(opts.Directives) > 0 {
		directives, err = finalizeExplicitDirectives(opts.Directives, opts.Count, opts.TypePreference)
		if err != nil {
			return nil, "", fmt.Errorf("quiz plan: %w", err)
		}
		if onProgress != nil {
			onProgress(ProgressEvent{Label: "Quiz plan", Detail: fmt.Sprintf("%d manual directive(s)", len(directives)), Done: true})
		}
	} else {
		orcProvider := provider
		if opts.ProviderOverrides != nil && opts.ProviderOverrides.Orchestrator != nil {
			orcProvider = opts.ProviderOverrides.Orchestrator
		}
		if isFocused {
			directives, err = runFocusedOrchestratorAgent(class, classProfileContext, candidates, opts.Count, opts.TypePreference, orcProvider, cfg, resolvedStore.Usage(), onProgress)
		} else {
			directives, err = runOrchestratorAgent(class, assessmentKind, classProfileContext, candidates, opts.Count, opts.TypePreference, orcProvider, cfg, resolvedStore.Usage(), onProgress)
		}
		if err != nil {
			return nil, "", fmt.Errorf("orchestrator: %w", err)
		}
	}

	directives = expandCompoundDirectives(directives)
	directives = normalizeDirectiveCount(directives, opts.Count)

	// ── 3. Component agents ──────────────────────────────────────────────────
	scoreByComponent := make(map[string]ComponentScore, len(candidates))
	for _, cs := range candidates {
		scoreByComponent[cs.Component.ID] = cs
	}
	directives = applyDirectiveDifficultyGuidance(directives, scoreByComponent)

	assignedIDs := make(map[string]bool, len(directives))
	for _, d := range directives {
		assignedIDs[d.ComponentID] = true
	}

	cmpProvider := provider
	if opts.ProviderOverrides != nil && opts.ProviderOverrides.Component != nil {
		cmpProvider = opts.ProviderOverrides.Component
	}

	var allSections []state.QuizSection
	var failedCount int
	for _, d := range directives {
		if strings.TrimSpace(d.ComponentID) == "" {
			failedCount += d.QuestionCount
			if onProgress != nil {
				onProgress(ProgressEvent{Label: "Quiz plan", Detail: "directive missing component_id", Done: true, Err: fmt.Errorf("directive missing component_id")})
			}
			continue
		}
		cs, ok := scoreByComponent[d.ComponentID]
		if !ok {
			failedCount += d.QuestionCount
			if onProgress != nil {
				onProgress(ProgressEvent{Label: "Quiz plan", Detail: fmt.Sprintf("component %s not found in class knowledge", d.ComponentID), Done: true, Err: fmt.Errorf("component %s not found", d.ComponentID)})
			}
			continue
		}
		if strings.TrimSpace(d.SectionID) == "" {
			d.SectionID = cs.Section.ID
		}
		if strings.TrimSpace(d.SectionTitle) == "" {
			d.SectionTitle = cs.Section.Title
		}
		sections, agentErr := runComponentQuestionAgent(assessmentKind, classProfileContext, d, cs, cmpProvider, cfg, resolvedStore.Usage(), onProgress)
		if agentErr != nil {
			if onProgress != nil {
				onProgress(ProgressEvent{Label: "Component " + d.ComponentID, Detail: agentErr.Error(), Done: true, Err: agentErr})
			}
			failedCount += d.QuestionCount
			continue
		}
		allSections = append(allSections, sections...)
	}

	if failedCount > 0 {
		for _, cs := range candidates {
			if failedCount <= 0 {
				break
			}
			if assignedIDs[cs.Component.ID] {
				continue
			}
			assignedIDs[cs.Component.ID] = true
			count := failedCount
			if count > 3 {
				count = 3
			}
			fallbackDir := OrchestratorDirective{
				ComponentID:   cs.Component.ID,
				SectionID:     cs.Section.ID,
				SectionTitle:  cs.Section.Title,
				QuestionCount: count,
				QuestionTypes: []string{opts.TypePreference},
				Angle:         "reinforce understanding",
			}
			sections, agentErr := runComponentQuestionAgent(assessmentKind, classProfileContext, fallbackDir, cs, cmpProvider, cfg, resolvedStore.Usage(), onProgress)
			if agentErr != nil {
				if onProgress != nil {
					onProgress(ProgressEvent{Label: "Fallback " + cs.Component.ID, Detail: agentErr.Error(), Done: true, Err: agentErr})
				}
				continue
			}
			allSections = append(allSections, sections...)
			failedCount -= count
		}
	}

	if len(allSections) == 0 {
		return nil, "", fmt.Errorf("no questions were generated — check provider configuration and logs")
	}

	allSections = filterDuplicateQuestionSections(allSections, recentSignals.QuestionKeys)
	if missing := opts.Count - len(allSections); missing > 0 {
		for _, cs := range candidates {
			if missing <= 0 {
				break
			}
			if assignedIDs[cs.Component.ID] {
				continue
			}
			assignedIDs[cs.Component.ID] = true

			count := missing
			if count > 2 {
				count = 2
			}
			extraDir := OrchestratorDirective{
				ComponentID:   cs.Component.ID,
				SectionID:     cs.Section.ID,
				SectionTitle:  cs.Section.Title,
				QuestionCount: count,
				QuestionTypes: []string{opts.TypePreference},
				Angle:         "novel scenario with different wording",
			}
			sections, agentErr := runComponentQuestionAgent(assessmentKind, classProfileContext, extraDir, cs, cmpProvider, cfg, resolvedStore.Usage(), onProgress)
			if agentErr != nil {
				if onProgress != nil {
					onProgress(ProgressEvent{Label: "Diversity fallback " + cs.Component.ID, Detail: agentErr.Error(), Done: true, Err: agentErr})
				}
				continue
			}
			filtered := filterDuplicateQuestionSections(sections, recentSignals.QuestionKeys)
			if len(filtered) == 0 {
				continue
			}
			allSections = append(allSections, filtered...)
			missing = opts.Count - len(allSections)
		}
	}

	if len(allSections) == 0 {
		return nil, "", fmt.Errorf("all generated questions duplicated recent history — broaden scope or increase question type diversity")
	}

	rebalanceChoiceAnswerPositions(allSections)
	deduplicateQuestionIDs(allSections)

	q := &state.Quiz{
		Title:    fmt.Sprintf("%s Adaptive %s", class, strings.Title(assessmentKind)),
		Class:    class,
		Sections: allSections,
	}
	normalizeQuizProvenance(q)

	return saveQuiz(class, assessmentKind, q)
}

// LoadQuiz reads and unmarshals a quiz YAML file from path.
func LoadQuiz(path string) (*state.Quiz, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read quiz file %q: %w", path, err)
	}
	var q state.Quiz
	if err := yaml.Unmarshal(data, &q); err != nil {
		return nil, fmt.Errorf("parse quiz file %q: %w", path, err)
	}
	return &q, nil
}

func saveQuiz(class, prefix string, q *state.Quiz) (*state.Quiz, string, error) {
	quizID := fmt.Sprintf("%s-%d", prefix, time.Now().Unix())
	quizPath, err := config.Path("quizzes", class, quizID+".yaml")
	if err != nil {
		return nil, "", err
	}
	if err := os.MkdirAll(filepath.Dir(quizPath), 0755); err != nil {
		return nil, "", fmt.Errorf("create quiz dir: %w", err)
	}
	data, err := yaml.Marshal(q)
	if err != nil {
		return nil, "", fmt.Errorf("marshal quiz: %w", err)
	}
	if err := os.WriteFile(quizPath, data, 0644); err != nil {
		return nil, "", fmt.Errorf("write quiz: %w", err)
	}
	sfqPath := strings.TrimSuffix(quizPath, ".yaml") + ".sfq"
	if err := os.WriteFile(sfqPath, quizToSFQ(q), 0644); err != nil {
		return nil, "", fmt.Errorf("write sfq file: %w", err)
	}
	return q, quizPath, nil
}

// quizToSFQ converts a Quiz to the .sfq block-delimiter format expected by the
// sfq binary.  Each QuizSection is rendered according to its question type so
// that all six sfq types (multiple-choice, multi-select, true-false,
// multi-true-false, short-answer, ordering) are natively supported.
func quizToSFQ(q *state.Quiz) []byte {
	var b strings.Builder
	if q.Title != "" {
		fmt.Fprintf(&b, "# %s\n\n", q.Title)
	}
	for _, sec := range q.Sections {
		b.WriteString("---\n")
		if sec.ID != "" {
			fmt.Fprintf(&b, "id: %s\n", sec.ID)
		}
		if sec.Type != "" {
			fmt.Fprintf(&b, "type: %s\n", sec.Type)
		}
		if sec.Hint != "" {
			fmt.Fprintf(&b, "hint: %q\n", sec.Hint)
		}
		if len(sec.Tags) > 0 {
			fmt.Fprintf(&b, "tags: [%s]\n", strings.Join(sec.Tags, ", "))
		}
		fmt.Fprintf(&b, "? %s\n", sec.Question)

		switch sec.Type {
		case "multiple-choice", "multi-select":
			for _, ch := range sec.Choices {
				mark := "[ ]"
				if ch.Correct {
					mark = "[x]"
				}
				fmt.Fprintf(&b, "- %s %s\n", mark, ch.Text)
			}
		case "true-false":
			if len(sec.Choices) >= 2 {
				for _, ch := range sec.Choices {
					mark := "[ ]"
					if ch.Correct {
						mark = "[x]"
					}
					fmt.Fprintf(&b, "- %s %s\n", mark, ch.Text)
				}
			} else if sec.Answer != "" {
				correct := strings.EqualFold(strings.TrimSpace(sec.Answer), "true")
				if correct {
					b.WriteString("- [x] True\n- [ ] False\n")
				} else {
					b.WriteString("- [ ] True\n- [x] False\n")
				}
			}
		case "multi-true-false":
			for _, ch := range sec.Choices {
				mark := "[F]"
				if ch.Correct {
					mark = "[T]"
				}
				fmt.Fprintf(&b, "- %s %s\n", mark, ch.Text)
			}
		case "ordering":
			for i, ch := range sec.Choices {
				fmt.Fprintf(&b, "%d. %s\n", i+1, ch.Text)
			}
		default:
			if sec.Answer != "" {
				fmt.Fprintf(&b, "answer: %q\n", sec.Answer)
			}
		}

		if sec.Reasoning != "" {
			fmt.Fprintf(&b, "explanation: %s\n", sec.Reasoning)
		}
		b.WriteString("\n")
	}
	b.WriteString("---\n")
	return []byte(b.String())
}
